#
# Makefile
#
# (c) 2025 Prof Dr Andreas Müller
#
all:	heartsuit.pdf clubsuit.pdf spadesuit.pdf diamondsuit.pdf

heartsuit.pdf:	heartsuit.tex
	pdflatex heartsuit.tex

clubsuit.pdf:	clubsuit.tex
	pdflatex clubsuit.tex

spadesuit.pdf:	spadesuit.tex
	pdflatex spadesuit.tex

diamondsuit.pdf:	diamondsuit.tex
	pdflatex diamondsuit.tex
