#
# Makefile.include
#
# (c) 2024 Prof Dr Andreas Müller
#
sourcesb =								\
	b-tabellen/chi2.tex						\
	b-tabellen/ftable.tex						\
	b-tabellen/ks.tex						\
	b-tabellen/norm.tex						\
	b-tabellen/normquant.tex					\
	b-tabellen/t.tex						\
	b-tabellen/tabellen.tex
