#
# Makefile -- build parts of the script
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
parts:	../skript.pdf
	pdfjam --outfile skript-00-intro.pdf ../skript.pdf 1-10
	pdfjam --outfile skript-01-chapter1.pdf ../skript.pdf 11-24 
	pdfjam --outfile skript-02-chapter2.pdf ../skript.pdf 25-64 
	pdfjam --outfile skript-03-chapter3.pdf ../skript.pdf 65-90 
	pdfjam --outfile skript-04-chapter4.pdf ../skript.pdf 91-108
	pdfjam --outfile skript-05-chapter5.pdf ../skript.pdf 109-150
	pdfjam --outfile skript-06-chapter6.pdf ../skript.pdf 151-152
	pdfjam --outfile skript-07-chapter7.pdf ../skript.pdf 153-154
	pdfjam --outfile skript-08-chapter8.pdf ../skript.pdf 155-156
	pdfjam --outfile skript-09-verteilungen.pdf ../skript.pdf 151-162
	pdfjam --outfile skript-10-tabellen.pdf ../skript.pdf 163-168
	pdfjam --outfile skript-11-index.pdf ../skript.pdf 169-170
