#
# Makefile -- build parts of the script
#
# (c) 2015 Prof Dr Andreas Mueller, Hochschule Rapperswil
#
parts:	../skript.pdf
	pdfjam --outfile skript-0-intro.pdf ../skript.pdf 1-10
	pdfjam --outfile skript-1-chapter1.pdf ../skript.pdf 11-24 
	pdfjam --outfile skript-2-chapter2.pdf ../skript.pdf 25-64 
	pdfjam --outfile skript-3-chapter3.pdf ../skript.pdf 65-90 
	pdfjam --outfile skript-4-chapter4.pdf ../skript.pdf 91-106
	pdfjam --outfile skript-5-chapter5.pdf ../skript.pdf 107-148
