#
# Makefile -- build the computation programs
#
# (c) 2020 Prof Dr Andreas Müller, Hochschule Rapperswil
#
binom:	binom.c
	gcc -o binom -Wall -O2 -g binom.c -lmpfr -lgmp
	./binom
	
small:	small.c
	gcc -o small -Wall -O2 -g small.c -lmpfr -lgmp
	./small

